# -*- coding: utf-8 -*-
"""whisper_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15g_SU9bYvdCSjx2YKaC9GGrprab6QGKl
"""

from openai import OpenAI

client = OpenAI(api_key="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")

audio_file= open("./testMp4.mp4", "rb")
transcript = client.audio.transcriptions.create(
  model="whisper-1",
  file=audio_file
)

transcript.text

